### ISSUE TITLE
Computer display for all machines that shows the status and effects of components

### ISSUE THREAD

**Issue by JamesKelly2294** [ThreeBeepsAndABoop/ProjectTPSupplyChain#13]
![IMG_4859](https://user-images.githubusercontent.com/6869609/79633246-1e418f80-8119-11ea-8fc7-17563b4f7eef.jpeg)

![IMG_4860](https://user-images.githubusercontent.com/6869609/79633250-226dad00-8119-11ea-8256-bb5cd71816b0.jpeg)

**Comment by Jacobingalls** [comment]
This machine has been made and been tied into the MachineController. It can now show all the relevant details of the Machine. This one was hard!
