### ISSUE TITLE
Create interface for Generator clients to request power status

### ISSUE THREAD

**Issue by JamesKelly2294** [ThreeBeepsAndABoop/ProjectTPSupplyChain#7]
My current thought on the API is that dependent machines should report 1. whether they are on or off and 2. their current power requirement.

The Generator will be responsible for checking against the client implementations in order to figure out what its energy level is.

A separate notification is sent to clients which will not be receiving power so that they can perform their own housekeeping/animations/etc. Similarly, a notification is sent when power is restored. This functionality can be reused for powering the client on/off.

**Comment by Jacobingalls** [comment]
This was implemented as part of the ResourceManager, though with a different strategy than above, and more general the "Power" as it handles other resources as well.
